# Generated by Django 3.2.4 on 2021-07-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20210728_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
    ]
