# Generated by Django 3.2.4 on 2021-07-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_auto_20210728_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(max_length=200, upload_to='perfil/fotos_perfil/', verbose_name='foto de perfil'),
        ),
    ]
