# Generated by Django 3.2.4 on 2021-07-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/fotos_perfil/', verbose_name='foto de perfil'),
        ),
    ]
