# Generated by Django 3.2.4 on 2021-07-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_fecha_creacion'),
        ('perfil', '0012_usuario_post_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='post_favoritos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='post_favoritos',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Post'),
        ),
    ]
