# Generated by Django 3.2.4 on 2021-07-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comentario',
            field=models.CharField(default='nada', max_length=500),
            preserve_default=False,
        ),
    ]
