# Generated by Django 3.2.4 on 2021-07-05 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ingrese el nombre del titulo', max_length=100)),
                ('fecha_creacion', models.DateField(default='05/07/2021')),
                ('content', models.TextField()),
                ('cateogoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.categoria')),
            ],
        ),
    ]
