# Generated by Django 3.2.4 on 2021-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210705_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.CharField(default='05/07/2021', max_length=50),
        ),
    ]
