# Generated by Django 3.2.4 on 2021-07-12 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('blog', '0004_auto_20210706_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredientes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.CharField(default='12/07/2021', max_length=50),
        ),
    ]
