# Generated by Django 3.2.4 on 2021-07-13 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('blog', '0005_auto_20210712_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.CharField(default='13/07/2021', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.producto'),
        ),
    ]
