# Generated by Django 3.2.4 on 2021-07-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('blog', '0007_auto_20210713_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredientes',
            field=models.ManyToManyField(to='catalogo.Producto'),
        ),
    ]
