# Generated by Django 3.2.4 on 2021-07-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
