# Generated by Django 3.2.4 on 2021-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_opinion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='fecha_creacion',
            field=models.DateField(default='<function now at 0x7fdc6509c8b0>'),
        ),
    ]
