# Generated by Django 3.2.4 on 2021-06-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_opinion_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='fecha_creacion',
        ),
    ]
