# Generated by Django 3.2.4 on 2021-06-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_opinion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='fecha_creacion',
            field=models.CharField(default='24/06/2021', max_length=50),
        ),
    ]
